export const types = {
  //Auth Actions//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  ERROR_CLEAN: 'ERROR_CLEAN',
  //Registration//
  REGISTER_USER_START: 'REGISTER_USER_START',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  //MAP_GEN//
  MAP_GEN_START: 'MAP_GEN_START',
  MAP_GEN_SUCCESS:'MAP_GEN_SUCCESS',
  MAP_GEN_FAILURE:'MAP_GEN_FAILURE',
  //MAP GET//
  MAP_GET_SUCCESS:'MAP_GET_SUCCESS',
  MAP_GET_START:'MAP_GET_START',
  MAP_GET_FAILURE:'MAP_GET_FAILURE',
  //Getting the UserName //
  USER_LOGIN_SUCCES: 'USER_LOGIN_SUCCESS',
  //Storing user information//
  INFO_START:'INFO_START',
  INFO_SUCCESS:'INFO_SUCCESS',
  INFO_FAILURE:'INFO_FAILURE',
};

export const ERROR = 'error';
